pub mod audio_fft;
pub mod audio_mouth_moving;
#[cfg(target_os = "linux")]
pub mod camera_reader;
pub mod facial_detection;
pub mod image_consumer;
pub mod mouth_moving;
pub mod plot_audio;
pub mod sound_reader;
