[package]
name = "ntpnet_lib"
version = "0.1.0"
edition = "2021"

[dependencies]

plotmux = { path = "../plotmux" }

clap = { version = "4.0.7", features = ["derive"] }
crossbeam-channel = "0.5.5"
itertools = "0.10.3"
tempfile = "3.3.0"
bimap = "0.6.2"
